[package]
name = "bcr-frontend-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
prost = "0.14.1"
pbjson = "0.9.0"
