[package]
name = "centrl-tools"
version = "0.1.0"
edition = "2021"
publish = false

# This package exists solely to make binary tools available to Bazel
# via @crates//:protoc-gen-*__bin

[dependencies]
protoc-gen-tonic = "0.5.0"
protoc-gen-prost = "0.5.0"
protoc-gen-prost-serde = "0.4.0"
