name: Trigger BCR Update via Repository Dispatch

on:
  repository_dispatch:
    types: [on-bcr-trigger]

jobs:
  trigger-update:
    uses: ./.github/workflows/update-bcr-submodule.yaml
    with:
      bcr_commit: ${{ github.event.client_payload.bcrCommitHash }}
    secrets: inherit
